// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smERP.Infrastructure.Data;

#nullable disable

namespace smERP.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BranchManagerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BranchManagerID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("LogoImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DepartmentHeadID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentHeadID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Attribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.AttributeValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeValueID")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AttributeID");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductAttribute", b =>
                {
                    b.Property<int>("ProductSKUID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeValueID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductSKUID", "AttributeValueID");

                    b.HasIndex("AttributeValueID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSKU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DiscountedPrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductSKUNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductVariantID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductSKUNumber")
                        .IsUnique();

                    b.ToTable("ProductSKUs");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSKUImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("ProductSKUID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductSKUID");

                    b.ToTable("ProductSKUImage");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSupplier", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("FirstTimeSupplied")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LastTimeSupplied")
                        .HasColumnType("date");

                    b.HasKey("ProductID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProductSuppliers");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.BaseTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountInCents")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int?>("TotalAmountInCents")
                        .HasColumnType("int");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("BaseTransaction");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.TransactionChange", b =>
                {
                    b.Property<int>("TransactionChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionChangeID"));

                    b.Property<int>("BaseTransactionID")
                        .HasColumnType("int");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.HasKey("TransactionChangeID");

                    b.HasIndex("BaseTransactionID");

                    b.ToTable("TransactionChanges");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.TransactionItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BaseTransactionID")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountInCents")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("PricePerUnitInCents")
                        .HasColumnType("int");

                    b.Property<int>("ProductSKUID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.Property<int>("UsableQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BaseTransactionID");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.BaseUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AddrsCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddrsDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddrsState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddrsStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalAmountOwedInCents")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.BuyTransaction", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.Transactions.BaseTransaction");

                    b.Property<int>("BaseTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("BaseTransactionID");

                    b.HasIndex("SupplierID");

                    b.ToTable("BuyTransactions");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.PaymentTransaction", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.Transactions.BaseTransaction");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ReferencingTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierID")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ReferencingTransactionID");

                    b.HasIndex("SupplierID");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.ProductMoveTransaction", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.Transactions.BaseTransaction");

                    b.Property<int>("FromBranchID")
                        .HasColumnType("int");

                    b.Property<string>("FromEmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ToBranchID")
                        .HasColumnType("int");

                    b.Property<string>("ToEmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("FromBranchID");

                    b.HasIndex("FromEmployeeID");

                    b.HasIndex("ToBranchID");

                    b.HasIndex("ToEmployeeID");

                    b.ToTable("ProductMoveTransactions");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.SellTransaction", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.Transactions.BaseTransaction");

                    b.Property<int>("BaseTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("BaseTransactionID");

                    b.HasIndex("CustomerID");

                    b.ToTable("SellTransactions");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Customer", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.User.BaseUser");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Employee", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.User.BaseUser");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryInCents")
                        .HasColumnType("int");

                    b.HasIndex("BranchID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Supplier", b =>
                {
                    b.HasBaseType("smERP.Domain.Entities.User.BaseUser");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Branch", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.Employee", "BranchManager")
                        .WithMany()
                        .HasForeignKey("BranchManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Organization.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchManager");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Department", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.Employee", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentHead");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.AttributeValue", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.Attribute", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Category", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Product", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductAttribute", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.AttributeValue", "AttributeValue")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("AttributeValueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Product.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Product.ProductSKU", "ProductSKU")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductSKUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");

                    b.Navigation("Product");

                    b.Navigation("ProductSKU");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSKU", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.Product", "Product")
                        .WithMany("ProductSKUs")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSKUImage", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.ProductSKU", "ProductSKU")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductSKUID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductSKU");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSupplier", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Product.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Supplier", "Supplier")
                        .WithMany("SuppliedProducts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.BaseTransaction", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Organization.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.TransactionChange", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", "BaseTransaction")
                        .WithMany("TransactionChanges")
                        .HasForeignKey("BaseTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTransaction");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.TransactionItem", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", "BaseTransaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("BaseTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTransaction");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.BuyTransaction", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", "BaseTransaction")
                        .WithMany()
                        .HasForeignKey("BaseTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.Transactions.BuyTransaction", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTransaction");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.PaymentTransaction", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.Transactions.PaymentTransaction", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", "ReferencingTransaction")
                        .WithMany("TransactionPayments")
                        .HasForeignKey("ReferencingTransactionID");

                    b.HasOne("smERP.Domain.Entities.User.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID");

                    b.Navigation("Customer");

                    b.Navigation("ReferencingTransaction");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.ProductMoveTransaction", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Organization.Branch", "FromBranch")
                        .WithMany()
                        .HasForeignKey("FromBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.Transactions.ProductMoveTransaction", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Organization.Branch", "ToBranch")
                        .WithMany()
                        .HasForeignKey("ToBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Employee", "ToEmployee")
                        .WithMany()
                        .HasForeignKey("ToEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBranch");

                    b.Navigation("FromEmployee");

                    b.Navigation("ToBranch");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.SellTransaction", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", "BaseTransaction")
                        .WithMany()
                        .HasForeignKey("BaseTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Transactions.BaseTransaction", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.Transactions.SellTransaction", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTransaction");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Customer", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.User.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Employee", b =>
                {
                    b.HasOne("smERP.Domain.Entities.Organization.Branch", "Branch")
                        .WithMany("BranchEmployees")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.Organization.Department", "Department")
                        .WithMany("DepartmentEmployees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smERP.Domain.Entities.User.Employee", "EmployeeManager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("EmployeeManagerId");

                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.User.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Department");

                    b.Navigation("EmployeeManager");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Supplier", b =>
                {
                    b.HasOne("smERP.Domain.Entities.User.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("smERP.Domain.Entities.User.Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Branch", b =>
                {
                    b.Navigation("BranchEmployees");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Organization.Department", b =>
                {
                    b.Navigation("DepartmentEmployees");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Attribute", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.AttributeValue", b =>
                {
                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.Product", b =>
                {
                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductSKUs");

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Product.ProductSKU", b =>
                {
                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("smERP.Domain.Entities.Transactions.BaseTransaction", b =>
                {
                    b.Navigation("TransactionChanges");

                    b.Navigation("TransactionItems");

                    b.Navigation("TransactionPayments");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Employee", b =>
                {
                    b.Navigation("ManagedEmployees");
                });

            modelBuilder.Entity("smERP.Domain.Entities.User.Supplier", b =>
                {
                    b.Navigation("SuppliedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
